INSERT INTO APP_USER (FIRST_NAME, LAST_NAME, ENCRYPTED_PASSWORD) VALUES ('Alice', 'Wonderland', 'root')
INSERT INTO APP_USER (FIRST_NAME, LAST_NAME, ENCRYPTED_PASSWORD) VALUES ('Bill', 'Moneyhead', 'root')

