INSERT INTO APP_USER (USER_NAME, ENCRYPTED_PASSWORD) VALUES ('Admin', '$2y$12$pkNTvpnfUmJ3IYixBcTuNeDZuc1uz.DMZ6j6/i0QY.9TkgANfjS0a');
INSERT INTO APP_USER (USER_NAME, ENCRYPTED_PASSWORD) VALUES ('Alice', '$2y$12$lRGeYYZQ8.fWjLLcQ8MyUOkmZ408ZEEO8xbkMVjllShGZLsEnuo2e');
INSERT INTO APP_USER (USER_NAME, ENCRYPTED_PASSWORD) VALUES ('Bob', '$2y$12$xEzt/urzbPLCkhE.LMANgeVWXeNmggFHaKo6XJFjxXHfeI2IWOm9i');
INSERT INTO APP_USER (USER_NAME, ENCRYPTED_PASSWORD) VALUES ('Jess', '$2y$12$jXdeoifi3knA7NMM8F3ajerGDS6baw.LO/dRKUFl1tNbaqvah1LrO');

INSERT INTO APP_ROLE (ROLE_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO APP_ROLE (ROLE_NAME) VALUES ('ROLE_USER');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1); -- User Admin ROLE_ADMIN
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 2); -- User Admin ROLE_USER
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 2); -- User Alice ROLE_USER
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (3, 2); -- USER Bob ROLE_USER
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (4, 2); -- USER Jess ROLE_USER

INSERT INTO CURRENCY (CODE, RATE, LAST_UPDATED) VALUES ('EUR', 1, '2020-12-30 13:00:00');
INSERT INTO CURRENCY (CODE, RATE, LAST_UPDATED) VALUES ('GBP', 0.9, '2020-12-30 13:00:00');
INSERT INTO CURRENCY (CODE, RATE, LAST_UPDATED) VALUES ('USD', 1.2, '2020-12-30 13:00:00');

INSERT INTO BANK_ACCOUNT (USER_ID, NAME, ACCOUNT_NUMBER, BALANCE, CURRENCY_ID) VALUES (1, 'Main Account (EUR)', 'AdmEur001', 5000, 1);
INSERT INTO BANK_ACCOUNT (USER_ID, NAME, ACCOUNT_NUMBER, BALANCE, CURRENCY_ID) VALUES (1, 'Savings Account (EUR)', 'AdmEur002', 2000, 1);
INSERT INTO BANK_ACCOUNT (USER_ID, NAME, ACCOUNT_NUMBER, BALANCE, CURRENCY_ID) VALUES (2, 'Main Account (EUR)', 'AlcEur001', 20000, 1);
INSERT INTO BANK_ACCOUNT (USER_ID, NAME, ACCOUNT_NUMBER, BALANCE, CURRENCY_ID) VALUES (3, 'Main Account (GBP)', 'BobGbp001', 20000, 2);
INSERT INTO BANK_ACCOUNT (USER_ID, NAME, ACCOUNT_NUMBER, BALANCE, CURRENCY_ID) VALUES (4, 'Main Account (USD)', 'JessUsd001', 200, 3);

INSERT INTO ACCOUNT_TRANSACTION (FROM_BA, TO_BA, REASON, SOURCE_CURRENCY_ID, ENDPOINT_CURRENCY_ID, SOURCE_AMOUNT, ENDPOINT_AMOUNT, TIME) VALUES (1, 2, 'Monthly Savings', 1, 1, 1000, 1000, '2020-09-01 13:00:32');
INSERT INTO ACCOUNT_TRANSACTION (FROM_BA, TO_BA, REASON, SOURCE_CURRENCY_ID, ENDPOINT_CURRENCY_ID, SOURCE_AMOUNT, ENDPOINT_AMOUNT, TIME) VALUES (1, 2, 'Monthly Savings', 1, 1, 1000, 1000, '2020-10-01 13:00:32');
INSERT INTO ACCOUNT_TRANSACTION (FROM_BA, TO_BA, REASON, SOURCE_CURRENCY_ID, ENDPOINT_CURRENCY_ID, SOURCE_AMOUNT, ENDPOINT_AMOUNT, TIME) VALUES (1, 2, 'Monthly Savings', 1, 1, 1000, 1000, '2020-11-01 13:00:32');
INSERT INTO ACCOUNT_TRANSACTION (FROM_BA, TO_BA, REASON, SOURCE_CURRENCY_ID, ENDPOINT_CURRENCY_ID, SOURCE_AMOUNT, ENDPOINT_AMOUNT, TIME) VALUES (1, 2, 'Monthly Savings', 1, 1, 1000, 1000, '2020-12-01 13:00:32');
INSERT INTO ACCOUNT_TRANSACTION (FROM_BA, TO_BA, REASON, SOURCE_CURRENCY_ID, ENDPOINT_CURRENCY_ID, SOURCE_AMOUNT, ENDPOINT_AMOUNT, TIME) VALUES (1, 3, 'Service Fee Technician Alice', 1, 1, 200, 200, '2020-12-15 14:00:32');
INSERT INTO ACCOUNT_TRANSACTION (FROM_BA, TO_BA, REASON, SOURCE_CURRENCY_ID, ENDPOINT_CURRENCY_ID, SOURCE_AMOUNT, ENDPOINT_AMOUNT, TIME) VALUES (5, 3, 'Service Fee Technician Alice', 3, 1, 97, 80, '2020-12-18 14:00:32');
INSERT INTO ACCOUNT_TRANSACTION (FROM_BA, TO_BA, REASON, SOURCE_CURRENCY_ID, ENDPOINT_CURRENCY_ID, SOURCE_AMOUNT, ENDPOINT_AMOUNT, TIME) VALUES (3, 4, 'Portuguese Lesson #1', 1, 2, 56, 50, '2020-11-13 14:00:32');
INSERT INTO ACCOUNT_TRANSACTION (FROM_BA, TO_BA, REASON, SOURCE_CURRENCY_ID, ENDPOINT_CURRENCY_ID, SOURCE_AMOUNT, ENDPOINT_AMOUNT, TIME) VALUES (3, 4, 'Portuguese Lesson #2', 1, 2, 56, 50, '2020-12-18 14:00:32');
INSERT INTO ACCOUNT_TRANSACTION (FROM_BA, TO_BA, REASON, SOURCE_CURRENCY_ID, ENDPOINT_CURRENCY_ID, SOURCE_AMOUNT, ENDPOINT_AMOUNT, TIME) VALUES (5, 1, 'Vacation spendings', 3, 1, 60, 50, '2020-12-18 14:00:32');
INSERT INTO ACCOUNT_TRANSACTION (FROM_BA, TO_BA, REASON, SOURCE_CURRENCY_ID, ENDPOINT_CURRENCY_ID, SOURCE_AMOUNT, ENDPOINT_AMOUNT, TIME) VALUES (1, 5, 'Vacation spendings', 1, 3, 40, 48, '2020-12-18 14:00:32');