INSERT INTO APP_USER (FIRST_NAME, LAST_NAME, ENCRYPTED_PASSWORD) VALUES ('Admin', 'Admin', 'root');
INSERT INTO APP_USER (FIRST_NAME, LAST_NAME, ENCRYPTED_PASSWORD) VALUES ('Alice', 'User', 'root');
INSERT INTO APP_USER (FIRST_NAME, LAST_NAME, ENCRYPTED_PASSWORD) VALUES ('Bob', 'User', 'root');

INSERT INTO APP_ROLE (ROLE_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO APP_ROLE (ROLE_NAME) VALUES ('ROLE_USER');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (3, 2);